### ISSUE TITLE
cl-authorize-net has implicit dependency on split-sequence

### ISSUE THREAD

**Issue by quicklisp** [AccelerationNet/cl-creditcard#1]
http://report.quicklisp.org/2015-01-04/failure-report/cl-creditcard.html#cl-authorize-net has the log. I get this:

```
;   READ error during COMPILE-FILE: Package SPLIT-SEQUENCE does not exist
```

**Comment by bobbysmith007** [comment]
pushed an unpushed patch... thanks!
